# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: julien <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/25 16:10:45 by julien            #+#    #+#              #
#    Updated: 2022/03/27 18:04:03 by julien           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #










# $@ nom cible
# $< nom premiere dependance
# $^ liste dependances
# $? liste dependances plus recentes que la cible
# $* nom fichier, sans extension
